# Generated by Django 3.2.6 on 2021-08-03 16:02

from django.db import migrations, models
import goods.Validators


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='star',
        ),
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.FloatField(default=None, null=True, validators=[goods.Validators.validate_score], verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
    ]
