# Generated by Django 3.2.6 on 2021-08-05 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0003_goods_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='staff',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='STAFF'),
        ),
    ]
