# Generated by Django 3.2.6 on 2021-08-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_goods_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='thumbnail',
            field=models.ImageField(default='photos/no_image.jpg', upload_to='photos/', verbose_name='THUMBNAIL'),
        ),
    ]
