# Generated by Django 3.2.6 on 2021-08-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_goods_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='thumbnail',
            field=models.ImageField(upload_to='photos/', verbose_name='THUMBNAIL'),
        ),
    ]
