# Generated by Django 3.2.6 on 2021-08-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210805_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default=None, max_length=50, verbose_name='customer_name'),
        ),
        migrations.AddField(
            model_name='order',
            name='sellphone',
            field=models.CharField(default=None, max_length=50, verbose_name='phonenumber'),
        ),
    ]
